### ISSUE TITLE
회원가입시 exception Handler처리

### ISSUE THREAD

**Issue by Thirdsense3** [Thirdsense3/StudyMatcher#9]
정해진 양식을 전부 입력하고, 확인하는 부분에서
```javascript
const res1 = await duplicateCheck(Nickname);

if (res1 !== 'possible id') {
      return alert('이미 등록된 ID 입니다.');
    }
```

이렇게 코드가 짜여져 있는데,
네트워크 에러로 res1의 값이 error data인 경우, modal창에 "이미 등록된 ID입니다 " 라는 로직으로 짜여져 있는 것으로 보입니다.

res1 변수 리턴 처리를 좀 더 세분화할 필요가 있는 것 같습니다.

**Comment by JihoonKwak** [comment]
해당 에러 메시지를 그대로 출력하도록 변경하였습니다.
